version: '2'

services:
  redis:
    image: redis:4-alpine

  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    ports:
     - 8000:80
    links:
     - backend
     - service1
     - service2
     - service3

  backend:
    build:
      context: .
      dockerfile: ./compose/backend/Dockerfile
    command: python backend.py
    volumes:
      - .:/app

  service1: &service
    build:
      context: .
      dockerfile: ./compose/backend/Dockerfile
    command: flask run --host=0.0.0.0 --port=5001
    environment:
      - FLASK_APP=service.py
      - BACKEND_URL=http://backend/
    links:
      - redis
      - backend
    volumes:
      - .:/app

  service2:
    <<: *service
    command: flask run --host=0.0.0.0 --port=5002

  service3:
    <<: *service
    command: flask run --host=0.0.0.0 --port=5003
