version: '2'

services:
  redis:
    image: redis:4-alpine

  backend:
    build:
      context: .
      dockerfile: ./compose/backend/Dockerfile
    command: python backend.py
    links:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:80"
